import type { KnmQuestion } from '../types';
import { newSrsState } from '../srs';

type Seed = Omit<KnmQuestion, 'srs' | 'createdAt'>;

const seeds: Seed[] = [
  {
    id: 'knm-geo-001',
    theme: 'geografie',
    questionNl: 'Wat is de hoofdstad van Nederland?',
    questionEn: 'What is the capital of the Netherlands?',
    choices: [
      { nl: 'Amsterdam', en: 'Amsterdam' },
      { nl: 'Den Haag', en: 'The Hague' },
      { nl: 'Rotterdam', en: 'Rotterdam' },
      { nl: 'Utrecht', en: 'Utrecht' },
    ],
    correctIndex: 0,
    explanationNl: 'Amsterdam is de hoofdstad. De regering zit in Den Haag.',
    explanationEn: 'Amsterdam is the capital. The government sits in The Hague.',
  },
  {
    id: 'knm-geo-002',
    theme: 'geografie',
    questionNl: 'Hoeveel provincies heeft Nederland?',
    questionEn: 'How many provinces does the Netherlands have?',
    choices: [{ nl: '10' }, { nl: '11' }, { nl: '12' }, { nl: '13' }],
    correctIndex: 2,
    explanationNl: 'Nederland heeft 12 provincies.',
    explanationEn: 'The Netherlands has 12 provinces.',
  },
  {
    id: 'knm-pol-001',
    theme: 'politiek',
    questionNl: 'Wie is het staatshoofd van Nederland?',
    questionEn: 'Who is the head of state of the Netherlands?',
    choices: [
      { nl: 'De minister-president', en: 'The prime minister' },
      { nl: 'De koning', en: 'The king' },
      { nl: 'De burgemeester', en: 'The mayor' },
      { nl: 'De president', en: 'The president' },
    ],
    correctIndex: 1,
    explanationNl: 'Nederland is een constitutionele monarchie. De koning is het staatshoofd.',
    explanationEn: 'The Netherlands is a constitutional monarchy. The king is the head of state.',
  },
  {
    id: 'knm-pol-002',
    theme: 'politiek',
    questionNl: 'Vanaf welke leeftijd mag je in Nederland stemmen?',
    questionEn: 'From what age can you vote in the Netherlands?',
    choices: [{ nl: '16 jaar' }, { nl: '17 jaar' }, { nl: '18 jaar' }, { nl: '21 jaar' }],
    correctIndex: 2,
    explanationNl: 'Je mag stemmen vanaf 18 jaar.',
    explanationEn: 'You can vote from age 18.',
  },
  {
    id: 'knm-cul-001',
    theme: 'cultuur',
    questionNl: 'Wanneer is Koningsdag?',
    questionEn: "When is King's Day?",
    choices: [
      { nl: '27 april', en: '27 April' },
      { nl: '30 april', en: '30 April' },
      { nl: '5 mei', en: '5 May' },
      { nl: '1 juli', en: '1 July' },
    ],
    correctIndex: 0,
    explanationNl: 'Koningsdag is op 27 april, de verjaardag van koning Willem-Alexander.',
    explanationEn: "King's Day is on 27 April, King Willem-Alexander's birthday.",
  },
  {
    id: 'knm-cul-002',
    theme: 'cultuur',
    questionNl: 'Welke kleuren heeft de Nederlandse vlag?',
    questionEn: 'What colors does the Dutch flag have?',
    choices: [
      { nl: 'Rood, wit, blauw', en: 'Red, white, blue' },
      { nl: 'Oranje, wit, blauw', en: 'Orange, white, blue' },
      { nl: 'Rood, wit, groen', en: 'Red, white, green' },
      { nl: 'Blauw, wit, rood', en: 'Blue, white, red' },
    ],
    correctIndex: 0,
    explanationNl: 'De Nederlandse vlag is rood, wit en blauw (van boven naar beneden).',
    explanationEn: 'The Dutch flag is red, white, and blue (top to bottom).',
  },
  {
    id: 'knm-werk-001',
    theme: 'werk-inkomen',
    questionNl: 'Wat moet je doen als je ziek bent en niet kunt werken?',
    questionEn: 'What should you do if you are sick and cannot work?',
    choices: [
      { nl: 'Naar het ziekenhuis gaan', en: 'Go to the hospital' },
      { nl: 'Niets doen', en: 'Do nothing' },
      { nl: 'Je werkgever bellen', en: 'Call your employer' },
      { nl: 'Een brief schrijven', en: 'Write a letter' },
    ],
    correctIndex: 2,
    explanationNl: 'Je moet je werkgever zo snel mogelijk bellen om te zeggen dat je ziek bent.',
    explanationEn: 'You must call your employer as soon as possible to say you are sick.',
  },
  {
    id: 'knm-werk-002',
    theme: 'werk-inkomen',
    questionNl: 'Wat is de WW?',
    questionEn: 'What is the WW?',
    choices: [
      { nl: 'Een werkgeversverzekering', en: "An employer's insurance" },
      { nl: 'Een werkloosheidsuitkering', en: 'An unemployment benefit' },
      { nl: 'Een woonwijk', en: 'A neighborhood' },
      { nl: 'Een werkvergunning', en: 'A work permit' },
    ],
    correctIndex: 1,
    explanationNl: 'WW (Werkloosheidswet) is een uitkering als je je baan verliest.',
    explanationEn: 'WW (Unemployment Act) is a benefit if you lose your job.',
  },
  {
    id: 'knm-won-001',
    theme: 'wonen',
    questionNl: 'Wat betaal je elke maand als je een huis huurt?',
    questionEn: 'What do you pay every month when you rent a house?',
    choices: [
      { nl: 'Belasting', en: 'Tax' },
      { nl: 'Huur', en: 'Rent' },
      { nl: 'Verzekering', en: 'Insurance' },
      { nl: 'Hypotheek', en: 'Mortgage' },
    ],
    correctIndex: 1,
    explanationNl: 'Als huurder betaal je maandelijks huur aan de verhuurder.',
    explanationEn: 'As a tenant you pay rent monthly to the landlord.',
  },
  {
    id: 'knm-gez-001',
    theme: 'gezondheidszorg',
    questionNl: 'Naar wie ga je eerst als je ziek bent?',
    questionEn: 'Who do you go to first when you are sick?',
    choices: [
      { nl: 'Naar het ziekenhuis', en: 'To the hospital' },
      { nl: 'Naar de specialist', en: 'To the specialist' },
      { nl: 'Naar de huisarts', en: 'To the GP (general practitioner)' },
      { nl: 'Naar de apotheek', en: 'To the pharmacy' },
    ],
    correctIndex: 2,
    explanationNl: 'De huisarts is de eerste dokter die je bezoekt. Hij of zij stuurt je zo nodig door.',
    explanationEn: 'The GP (huisarts) is the first doctor you visit. They refer you on if needed.',
  },
  {
    id: 'knm-gez-002',
    theme: 'gezondheidszorg',
    questionNl: 'Wat is een zorgverzekering verplicht voor iedereen in Nederland vanaf welke leeftijd?',
    questionEn: 'From what age is health insurance compulsory for everyone in the Netherlands?',
    choices: [{ nl: '14 jaar' }, { nl: '16 jaar' }, { nl: '18 jaar' }, { nl: '21 jaar' }],
    correctIndex: 2,
    explanationNl: 'Vanaf 18 jaar moet iedereen in Nederland een zorgverzekering hebben.',
    explanationEn: 'From age 18 everyone in the Netherlands must have health insurance.',
  },
  {
    id: 'knm-ond-001',
    theme: 'onderwijs',
    questionNl: 'Tot welke leeftijd zijn kinderen leerplichtig in Nederland?',
    questionEn: 'Until what age are children required to attend school in the Netherlands?',
    choices: [{ nl: '14 jaar' }, { nl: '16 jaar' }, { nl: '18 jaar' }, { nl: '21 jaar' }],
    correctIndex: 1,
    explanationNl: 'Kinderen zijn leerplichtig tot 16 jaar. Tot 18 jaar geldt de kwalificatieplicht (zonder startkwalificatie).',
    explanationEn: 'Children must attend school until age 16. Until 18, the qualification requirement applies if they have no starting qualification.',
  },
  {
    id: 'knm-rech-001',
    theme: 'rechten-plichten',
    questionNl: 'Wat is een BSN?',
    questionEn: 'What is a BSN?',
    choices: [
      { nl: 'Een bankrekeningnummer', en: 'A bank account number' },
      { nl: 'Een Burgerservicenummer', en: 'A citizen service number' },
      { nl: 'Een belastingformulier', en: 'A tax form' },
      { nl: 'Een buurthuis', en: 'A community center' },
    ],
    correctIndex: 1,
    explanationNl: 'BSN is je persoonlijke nummer bij de overheid. Je hebt het nodig voor werk, zorg en belasting.',
    explanationEn: 'BSN is your personal government number. You need it for work, healthcare, and tax.',
  },
  {
    id: 'knm-rech-002',
    theme: 'rechten-plichten',
    questionNl: 'Vanaf welke leeftijd mag je in Nederland alcohol kopen?',
    questionEn: 'From what age can you buy alcohol in the Netherlands?',
    choices: [{ nl: '16 jaar' }, { nl: '17 jaar' }, { nl: '18 jaar' }, { nl: '21 jaar' }],
    correctIndex: 2,
    explanationNl: 'Vanaf 18 jaar mag je alcohol kopen.',
    explanationEn: 'From age 18 you can buy alcohol.',
  },
  {
    id: 'knm-dag-001',
    theme: 'dagelijks-leven',
    questionNl: 'Wat is DigiD?',
    questionEn: 'What is DigiD?',
    choices: [
      { nl: 'Een digitale krant', en: 'A digital newspaper' },
      { nl: 'Een inlogcode voor overheidswebsites', en: 'A login for government websites' },
      { nl: 'Een soort bankpas', en: 'A type of bank card' },
      { nl: 'Een digitale tv-kanaal', en: 'A digital TV channel' },
    ],
    correctIndex: 1,
    explanationNl: 'Met DigiD log je in op websites van de overheid (zoals DUO, Belastingdienst, gemeente).',
    explanationEn: 'With DigiD you log in to government websites (like DUO, the tax office, your municipality).',
  },
];

export const KNM_SEEDS: KnmQuestion[] = seeds.map((s) => ({
  ...s,
  srs: newSrsState(),
  createdAt: Date.now(),
}));
