import type { Lesson } from '@/lib/types';

export const A0_LES_14: Lesson = {
  id: 'a0-les-14',
  track: 'beginner',
  level: 'A0',
  order: 14,
  titleNl: 'Familie',
  titleEn: 'Family',
  estimatedMinutes: 14,
  coverage: ['§2.5'],
  prerequisites: ['a0-les-13'],
  sections: [
    {
      id: 'woorden-1',
      type: 'woorden',
      payload: {
        intro:
          'Zeventien familiewoorden. Bijna allemaal "de" — alleen "het kind" is een uitzondering, maar in meervoud wordt het "de kinderen" (alle meervouden zijn de, uit Les 13).',
        words: [
          {
            nl: 'familie',
            en: 'family',
            gender: 'de',
            audioId: 'familie',
            exampleNl: 'Mijn familie woont in Nederland.',
            exampleEn: 'My family lives in the Netherlands.',
          },
          {
            nl: 'vader',
            en: 'father',
            gender: 'de',
            audioId: 'vader',
            exampleNl: 'Mijn vader heet Jan.',
            exampleEn: 'My father is named Jan.',
          },
          {
            nl: 'moeder',
            en: 'mother',
            gender: 'de',
            audioId: 'moeder',
            exampleNl: 'Mijn moeder komt uit België.',
            exampleEn: 'My mother comes from Belgium.',
          },
          {
            nl: 'zoon',
            en: 'son',
            gender: 'de',
            audioId: 'zoon',
            exampleNl: 'Hij heeft één zoon.',
            exampleEn: 'He has one son.',
          },
          {
            nl: 'dochter',
            en: 'daughter',
            gender: 'de',
            audioId: 'dochter',
            exampleNl: 'Zij heeft twee dochters.',
            exampleEn: 'She has two daughters.',
          },
          {
            nl: 'broer',
            en: 'brother',
            gender: 'de',
            audioId: 'broer',
            exampleNl: 'Mijn broer heet Tom.',
            exampleEn: 'My brother is named Tom.',
          },
          {
            nl: 'zus',
            en: 'sister',
            gender: 'de',
            audioId: 'zus',
            exampleNl: 'Ik heb één zus.',
            exampleEn: 'I have one sister.',
          },
          {
            nl: 'kind',
            en: 'child',
            gender: 'het',
            audioId: 'kind',
            exampleNl: 'Het kind heeft een boek. (meervoud: de kinderen)',
            exampleEn: 'The child has a book. (plural: de kinderen)',
          },
          {
            nl: 'baby',
            en: 'baby',
            gender: 'de',
            audioId: 'baby',
            exampleNl: 'De baby slaapt.',
            exampleEn: 'The baby sleeps.',
          },
          {
            nl: 'opa',
            en: 'grandfather',
            gender: 'de',
            audioId: 'opa',
            exampleNl: 'Mijn opa is tachtig jaar.',
            exampleEn: 'My grandfather is eighty years old.',
          },
          {
            nl: 'oma',
            en: 'grandmother',
            gender: 'de',
            audioId: 'oma',
            exampleNl: 'Mijn oma woont in Rotterdam.',
            exampleEn: 'My grandmother lives in Rotterdam.',
          },
          {
            nl: 'oom',
            en: 'uncle',
            gender: 'de',
            audioId: 'oom',
            exampleNl: 'Mijn oom komt uit Spanje.',
            exampleEn: 'My uncle comes from Spain.',
          },
          {
            nl: 'tante',
            en: 'aunt',
            gender: 'de',
            audioId: 'tante',
            exampleNl: 'Mijn tante heet Lisa.',
            exampleEn: 'My aunt is named Lisa.',
          },
          {
            nl: 'vriend',
            en: 'friend (male) / boyfriend',
            gender: 'de',
            audioId: 'vriend',
            exampleNl: 'Mijn vriend heet Peter.',
            exampleEn: 'My friend is named Peter.',
          },
          {
            nl: 'vriendin',
            en: 'friend (female) / girlfriend',
            gender: 'de',
            audioId: 'vriendin',
            exampleNl: 'Mijn vriendin heet Anna.',
            exampleEn: 'My friend is named Anna.',
          },
          {
            nl: 'man',
            en: 'man / husband',
            gender: 'de',
            audioId: 'man-fam',
            exampleNl: 'De man is mijn vader.',
            exampleEn: 'The man is my father.',
          },
          {
            nl: 'vrouw',
            en: 'woman / wife',
            gender: 'de',
            audioId: 'vrouw',
            exampleNl: 'De vrouw is mijn moeder.',
            exampleEn: 'The woman is my mother.',
          },
        ],
      },
    },
    {
      id: 'de-het-1',
      type: 'de-het',
      payload: {
        intro:
          'Tien familiewoorden door elkaar. Bijna alles is "de" — let goed op de enige uitzondering.',
        items: [
          { nl: 'vader', gender: 'de', en: 'father' },
          { nl: 'moeder', gender: 'de', en: 'mother' },
          { nl: 'kind', gender: 'het', en: 'child' },
          { nl: 'broer', gender: 'de', en: 'brother' },
          { nl: 'zus', gender: 'de', en: 'sister' },
          { nl: 'opa', gender: 'de', en: 'grandfather' },
          { nl: 'oma', gender: 'de', en: 'grandmother' },
          { nl: 'familie', gender: 'de', en: 'family' },
          { nl: 'baby', gender: 'de', en: 'baby' },
          { nl: 'vrouw', gender: 'de', en: 'woman / wife' },
        ],
      },
    },
    {
      id: 'spreken-1',
      type: 'spreken',
      payload: {
        intro:
          'Vier zinnen over jouw familie. Beluister het model, vervang de namen en plaatsen door je eigen gegevens, en neem op. "Mijn" is het bezittelijk voornaamwoord — net als jouw/uw, maar voor jezelf.',
        lines: [
          {
            id: 'l1',
            nl: 'Mijn vader heet Jan.',
            en: 'My father is named Jan.',
            audioId: 'spreken-fam-vader',
          },
          {
            id: 'l2',
            nl: 'Mijn moeder komt uit Nederland.',
            en: 'My mother comes from the Netherlands.',
            audioId: 'spreken-fam-moeder',
          },
          {
            id: 'l3',
            nl: 'Ik heb één broer en twee zussen.',
            en: 'I have one brother and two sisters.',
            audioId: 'spreken-fam-broer-zussen',
          },
          {
            id: 'l4',
            nl: 'Mijn opa en oma wonen in Den Haag.',
            en: 'My grandfather and grandmother live in The Hague.',
            audioId: 'spreken-fam-opa-oma',
          },
        ],
      },
    },
    {
      id: 'schrijven-1',
      type: 'schrijven',
      payload: {
        intro:
          'Schrijf vijf zinnen over één familielid. Geen goed/fout — vergelijk met het model. Houd het simpel: één feit per zin.',
        items: [
          {
            promptEn: "Write your father's (or another male relative's) name.",
            expected: 'Mijn vader heet Jan.',
            hint: 'gebruik "Mijn vader/broer/oom heet …"',
          },
          {
            promptEn: "Write your mother's (or another female relative's) age.",
            expected: 'Mijn moeder is vijftig jaar oud.',
            hint: 'gebruik "Mijn moeder/zus/oma is … jaar oud"',
          },
          {
            promptEn: 'Write where your sister or brother lives.',
            expected: 'Mijn zus woont in Amsterdam.',
            hint: 'gebruik "Mijn zus/broer woont in …"',
          },
          {
            promptEn: 'Write where one grandparent comes from.',
            expected: 'Mijn oma komt uit België.',
            hint: 'gebruik "Mijn opa/oma komt uit …"',
          },
          {
            promptEn: 'Write how many siblings (broers/zussen) you have.',
            expected: 'Ik heb één broer en twee zussen.',
            hint: 'gebruik "Ik heb [getal] broer(s)/zus(sen)"',
          },
        ],
      },
    },
  ],
};
