import type { Lesson } from '@/lib/types';

export const A0_LES_22: Lesson = {
  id: 'a0-les-22',
  track: 'beginner',
  level: 'A0',
  order: 22,
  titleNl: 'Eten & drinken — in het café',
  titleEn: 'Food & drinks — at the café',
  estimatedMinutes: 14,
  coverage: ['§2.8', '§4'],
  prerequisites: ['a0-les-21'],
  sections: [
    {
      id: 'woorden-1',
      type: 'woorden',
      payload: {
        intro:
          'Vijf drankjes en zeven basis-etenswaren, plus de twee belangrijkste werkwoorden (eten, drinken). Lidwoord-mix: koffie, thee, melk, wijn, kaas, boter, ham zijn "de"; water, sap, bier, brood, ei zijn "het" (dranken zonder vorm en stoffen worden vaak "het").',
        words: [
          {
            nl: 'water',
            en: 'water',
            gender: 'het',
            audioId: 'water',
            exampleNl: 'Ik drink water.',
            exampleEn: 'I drink water.',
          },
          {
            nl: 'koffie',
            en: 'coffee',
            gender: 'de',
            audioId: 'koffie',
            exampleNl: 'Een koffie, alstublieft.',
            exampleEn: 'A coffee, please.',
          },
          {
            nl: 'thee',
            en: 'tea',
            gender: 'de',
            audioId: 'thee',
            exampleNl: 'Mijn moeder drinkt thee.',
            exampleEn: 'My mother drinks tea.',
          },
          {
            nl: 'melk',
            en: 'milk',
            gender: 'de',
            audioId: 'melk',
            exampleNl: 'Koffie met melk, graag.',
            exampleEn: 'Coffee with milk, please.',
          },
          {
            nl: 'sap',
            en: 'juice',
            gender: 'het',
            audioId: 'sap',
            exampleNl: 'Het kind drinkt sap.',
            exampleEn: 'The child drinks juice.',
          },
          {
            nl: 'bier',
            en: 'beer',
            gender: 'het',
            audioId: 'bier',
            exampleNl: 'Een bier, alstublieft.',
            exampleEn: 'A beer, please.',
          },
          {
            nl: 'wijn',
            en: 'wine',
            gender: 'de',
            audioId: 'wijn',
            exampleNl: 'Witte of rode wijn?',
            exampleEn: 'White or red wine?',
          },
          {
            nl: 'brood',
            en: 'bread',
            gender: 'het',
            audioId: 'brood',
            exampleNl: 'Ik eet brood met kaas.',
            exampleEn: 'I eat bread with cheese.',
          },
          {
            nl: 'kaas',
            en: 'cheese',
            gender: 'de',
            audioId: 'kaas',
            exampleNl: 'Nederlandse kaas is bekend.',
            exampleEn: 'Dutch cheese is well-known.',
          },
          {
            nl: 'boter',
            en: 'butter',
            gender: 'de',
            audioId: 'boter',
            exampleNl: 'Brood met boter, graag.',
            exampleEn: 'Bread with butter, please.',
          },
          {
            nl: 'ham',
            en: 'ham',
            gender: 'de',
            audioId: 'ham',
            exampleNl: 'Een broodje met ham en kaas.',
            exampleEn: 'A sandwich with ham and cheese.',
          },
          {
            nl: 'ei',
            en: 'egg',
            gender: 'het',
            audioId: 'ei-eten',
            exampleNl: 'Ik eet een ei. (meervoud: eieren)',
            exampleEn: 'I eat an egg. (plural: eieren)',
          },
          {
            nl: 'drinken',
            en: 'to drink',
            audioId: 'drinken',
            exampleNl: 'Wat wil je drinken?',
            exampleEn: 'What do you want to drink?',
          },
          {
            nl: 'eten',
            en: 'to eat',
            audioId: 'eten',
            exampleNl: 'Ik eet brood om acht uur.',
            exampleEn: 'I eat bread at eight o\'clock.',
          },
        ],
      },
    },
    {
      id: 'de-het-1',
      type: 'de-het',
      payload: {
        intro:
          'Tien eet- en drinkwoorden door elkaar. "Stoffen" (water, sap, bier, brood) zijn vaak "het"; bereide dranken (koffie, thee, wijn) blijken "de". Geen sluitende regel — leer per woord.',
        items: [
          { nl: 'water', gender: 'het', en: 'water' },
          { nl: 'koffie', gender: 'de', en: 'coffee' },
          { nl: 'thee', gender: 'de', en: 'tea' },
          { nl: 'sap', gender: 'het', en: 'juice' },
          { nl: 'bier', gender: 'het', en: 'beer' },
          { nl: 'wijn', gender: 'de', en: 'wine' },
          { nl: 'brood', gender: 'het', en: 'bread' },
          { nl: 'kaas', gender: 'de', en: 'cheese' },
          { nl: 'ham', gender: 'de', en: 'ham' },
          { nl: 'melk', gender: 'de', en: 'milk' },
        ],
      },
    },
    {
      id: 'dialoog-1',
      type: 'mini-dialoog',
      payload: {
        intro:
          'In een café — de klant bestelt, de ober antwoordt formeel met "u". "Graag" en "alstublieft" zijn de twee beleefdheidswoorden die je dagelijks nodig hebt.',
        scenes: [
          {
            id: 'cafe',
            titleNl: 'In het café',
            titleEn: 'At the café',
            register: 'formeel',
            lines: [
              {
                id: 'l1',
                speaker: 'Ober',
                nl: 'Goedendag. Wat mag het zijn?',
                en: 'Good day. What would you like?',
                audioId: 'dialoog-cafe-l1',
              },
              {
                id: 'l2',
                speaker: 'Klant',
                nl: 'Een koffie graag, met melk.',
                en: 'A coffee please, with milk.',
                audioId: 'dialoog-cafe-l2',
              },
              {
                id: 'l3',
                speaker: 'Ober',
                nl: 'En verder nog iets?',
                en: 'And anything else?',
                audioId: 'dialoog-cafe-l3',
              },
              {
                id: 'l4',
                speaker: 'Klant',
                nl: 'Een broodje met kaas, alstublieft.',
                en: 'A cheese sandwich, please.',
                audioId: 'dialoog-cafe-l4',
              },
              {
                id: 'l5',
                speaker: 'Ober',
                nl: 'Komt eraan.',
                en: 'Coming right up.',
                audioId: 'dialoog-cafe-l5',
              },
            ],
          },
        ],
      },
    },
    {
      id: 'spreken-1',
      type: 'spreken',
      payload: {
        intro:
          'Vier bestellingen om hardop te oefenen. Vervang het ene drankje of broodje door wat jij graag wilt. "Graag" achter de bestelling klinkt netjes; "alstublieft" is iets formeler.',
        lines: [
          {
            id: 'l1',
            nl: 'Een koffie graag.',
            en: 'A coffee please.',
            audioId: 'spreken-cafe-l1',
          },
          {
            id: 'l2',
            nl: 'Voor mij een thee met melk, alstublieft.',
            en: 'For me a tea with milk, please.',
            audioId: 'spreken-cafe-l2',
          },
          {
            id: 'l3',
            nl: 'Ik wil graag een glas water.',
            en: 'I would like a glass of water.',
            audioId: 'spreken-cafe-l3',
          },
          {
            id: 'l4',
            nl: 'Een broodje met ham en kaas, graag.',
            en: 'A ham and cheese sandwich, please.',
            audioId: 'spreken-cafe-l4',
          },
        ],
      },
    },
  ],
};
