import type { Lesson } from '@/lib/types';

export const A0_LES_15: Lesson = {
  id: 'a0-les-15',
  track: 'beginner',
  level: 'A0',
  order: 15,
  titleNl: 'Het lichaam',
  titleEn: 'The body',
  estimatedMinutes: 13,
  coverage: ['§2.6'],
  prerequisites: ['a0-les-14'],
  sections: [
    {
      id: 'woorden-1',
      type: 'woorden',
      payload: {
        intro:
          'Veertien lichaamsdelen. Let op de paren enkelvoud/meervoud bij wat we in tweetallen hebben: oog/ogen, oor/oren, tand/tanden, hand/handen, voet/voeten. Bij "haar" (het haar = hoofdhaar) niet verwarren met "haar" als bezittelijk voornaamwoord (her).',
        words: [
          {
            nl: 'hoofd',
            en: 'head',
            gender: 'het',
            audioId: 'hoofd',
            exampleNl: 'Ik heb pijn aan mijn hoofd.',
            exampleEn: 'My head hurts.',
          },
          {
            nl: 'haar',
            en: 'hair',
            gender: 'het',
            audioId: 'haar',
            exampleNl: 'Hij heeft bruin haar.',
            exampleEn: 'He has brown hair.',
          },
          {
            nl: 'oog',
            en: 'eye',
            gender: 'het',
            audioId: 'oog',
            exampleNl: 'Mijn oog doet pijn. (meervoud: de ogen)',
            exampleEn: 'My eye hurts. (plural: de ogen)',
          },
          {
            nl: 'oor',
            en: 'ear',
            gender: 'het',
            audioId: 'oor',
            exampleNl: 'Ik hoor met mijn oor. (meervoud: de oren)',
            exampleEn: 'I hear with my ear. (plural: de oren)',
          },
          {
            nl: 'neus',
            en: 'nose',
            gender: 'de',
            audioId: 'neus',
            exampleNl: 'Mijn neus is koud.',
            exampleEn: 'My nose is cold.',
          },
          {
            nl: 'mond',
            en: 'mouth',
            gender: 'de',
            audioId: 'mond',
            exampleNl: 'Doe je mond open.',
            exampleEn: 'Open your mouth.',
          },
          {
            nl: 'tand',
            en: 'tooth',
            gender: 'de',
            audioId: 'tand',
            exampleNl: 'Ik heb pijn aan mijn tand. (meervoud: de tanden)',
            exampleEn: 'My tooth hurts. (plural: de tanden)',
          },
          {
            nl: 'hand',
            en: 'hand',
            gender: 'de',
            audioId: 'hand',
            exampleNl: 'Geef mij je hand. (meervoud: de handen)',
            exampleEn: 'Give me your hand. (plural: de handen)',
          },
          {
            nl: 'arm',
            en: 'arm',
            gender: 'de',
            audioId: 'arm',
            exampleNl: 'Mijn arm is moe.',
            exampleEn: 'My arm is tired.',
          },
          {
            nl: 'been',
            en: 'leg',
            gender: 'het',
            audioId: 'been',
            exampleNl: 'Ik heb pijn in mijn been.',
            exampleEn: 'My leg hurts.',
          },
          {
            nl: 'voet',
            en: 'foot',
            gender: 'de',
            audioId: 'voet',
            exampleNl: 'Mijn voet is koud. (meervoud: de voeten)',
            exampleEn: 'My foot is cold. (plural: de voeten)',
          },
          {
            nl: 'buik',
            en: 'belly / stomach',
            gender: 'de',
            audioId: 'buik',
            exampleNl: 'Ik heb pijn in mijn buik.',
            exampleEn: 'My stomach hurts.',
          },
          {
            nl: 'rug',
            en: 'back',
            gender: 'de',
            audioId: 'rug',
            exampleNl: 'Mijn rug doet pijn.',
            exampleEn: 'My back hurts.',
          },
          {
            nl: 'hart',
            en: 'heart',
            gender: 'het',
            audioId: 'hart',
            exampleNl: 'Mijn hart klopt snel.',
            exampleEn: 'My heart beats fast.',
          },
        ],
      },
    },
    {
      id: 'de-het-1',
      type: 'de-het',
      payload: {
        intro:
          'Tien lichaamsdelen door elkaar. Lichaamsdelen zijn gemengd: zes "het"-woorden (hoofd, haar, oog, oor, been, hart) tegen acht "de" — typischer dan de familie-lijst.',
        items: [
          { nl: 'hoofd', gender: 'het', en: 'head' },
          { nl: 'haar', gender: 'het', en: 'hair' },
          { nl: 'oog', gender: 'het', en: 'eye' },
          { nl: 'hart', gender: 'het', en: 'heart' },
          { nl: 'been', gender: 'het', en: 'leg' },
          { nl: 'neus', gender: 'de', en: 'nose' },
          { nl: 'mond', gender: 'de', en: 'mouth' },
          { nl: 'hand', gender: 'de', en: 'hand' },
          { nl: 'voet', gender: 'de', en: 'foot' },
          { nl: 'rug', gender: 'de', en: 'back' },
        ],
      },
    },
    {
      id: 'luisteren-1',
      type: 'luisteren',
      payload: {
        intro:
          'Iemand vertelt waar ze pijn hebben. Luister en beantwoord drie ja-of-nee vragen. Beluister meerdere keren — het transcript blijft verstopt tot je het opvraagt.',
        audioId: 'luisteren-pijn',
        transcriptNl: 'Ik heb pijn aan mijn hoofd, in mijn buik en in mijn rug.',
        transcriptEn: 'I have pain in my head, in my stomach and in my back.',
        questions: [
          {
            questionNl: 'Heeft de spreker pijn aan zijn hoofd?',
            choices: ['ja', 'nee'],
            correctIndex: 0,
          },
          {
            questionNl: 'Heeft de spreker pijn aan zijn buik?',
            choices: ['ja', 'nee'],
            correctIndex: 0,
          },
          {
            questionNl: 'Heeft de spreker pijn aan zijn voet?',
            choices: ['ja', 'nee'],
            correctIndex: 1,
          },
        ],
      },
    },
    {
      id: 'spreken-1',
      type: 'spreken',
      payload: {
        intro:
          'Vier zinnen waarin je een lichaamsdeel beschrijft of een klacht uit. De laatste twee bevatten kleuren — een voorproefje op Les 24. Je hoeft de kleurverbuiging nog niet te begrijpen; luisteren en napraten is genoeg.',
        lines: [
          {
            id: 'l1',
            nl: 'Ik heb pijn aan mijn hoofd.',
            en: 'My head hurts.',
            audioId: 'spreken-lich-hoofd',
          },
          {
            id: 'l2',
            nl: 'Ik heb pijn in mijn rug.',
            en: 'My back hurts.',
            audioId: 'spreken-lich-rug',
          },
          {
            id: 'l3',
            nl: 'Hij heeft bruin haar.',
            en: 'He has brown hair.',
            audioId: 'spreken-lich-haar',
          },
          {
            id: 'l4',
            nl: 'Zij heeft blauwe ogen.',
            en: 'She has blue eyes.',
            audioId: 'spreken-lich-ogen',
          },
        ],
      },
    },
  ],
};
